name: First CI Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print a message
        run: echo "Hello, BobApp CI is running!"
